name: Build

on: push

defaults:
  run:
    shell: bash

jobs:
  Build:
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: Win32
            env: Win32
          - os: windows-latest
            arch: Win64
            env: Win64
          - os: ubuntu-18.04
            arch: x64
            env: Linux
          #- os: ubuntu-18.04
            #arch: x86
            #env: Linux

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Directories"
        run: mkdir output output/lib output/include

      - name: "Configure Arguments"
        run: |
          echo "::set-env name=OUTPUT_DIR::$PWD/output"
          scripts/${{ matrix.env }}.sh
          echo "::set-env name=CMAKE_CONFIGURE_ARGS::$CMAKE_CONFIGURE_ARGS -DCMAKE_INSTALL_PREFIX=$PWD/output -DCMAKE_PREFIX_PATH=$PWD/output"

      - name: "Windows: Setup VS Dev Environment"
        if: ${{ matrix.os == 'windows-latest' }}
        uses: seanmiddleditch/gha-setup-vsdevenv@v1
        with:
          arch: ${{ env.VS_ARCH }}

      - name: "Linux: Setup Dependencies"
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: DEBIAN_FRONTEND=noninteractive sudo apt-get -y --no-install-recommends install libgl-dev

      - name: Build zlib
        run: |
          scripts/build.sh zlib

      - name: Build non-Windows
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          scripts/build.sh libpng
          scripts/build.sh libjpeg-turbo
          scripts/build.sh openssl

      - name: Build
        run: |
          scripts/build.sh glew
          scripts/build.sh SDL2
          scripts/build.sh SDL2_mixer
          scripts/build.sh freetype -DCMAKE_DISABLE_FIND_PACKAGE_HarfBuzz=TRUE
          scripts/build.sh harfbuzz
          scripts/build.sh freetype


      - name: Result
        run: ls -R output

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.env }}-${{ matrix.arch }}
          path: |
            output/*
