name: Build

on: push

defaults:
  run:
    shell: bash

jobs:
  Build:
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: x86
            env: Windows
          - os: windows-latest
            arch: x64
            env: Windows
          - os: ubuntu-18.04
            arch: x64
            env: Linux
          #- os: ubuntu-18.04
            #arch: x86
            #env: Linux

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Directories"
        run: mkdir output output/lib output/include

      - name: "Configure Arguments"
        run: |
          echo "::set-env name=OUTPUT_DIR::$PWD/output"
          platforms/${{ matrix.env }}.sh
          platforms/${{ matrix.env }}-${{ matrix.arch }}.sh
          echo "::set-env name=CMAKE_CONFIGURE_ARGS::$CMAKE_CONFIGURE_ARGS -DCMAKE_INSTALL_PREFIX=$PWD/output -DCMAKE_PREFIX_PATH=$PWD/output"

      - name: "Windows: Setup VS Dev Environment"
        if: ${{ matrix.os == 'windows-latest' }}
        uses: seanmiddleditch/gha-setup-vsdevenv@v1
        with:
          arch: ${{ env.VS_ARCH }}

      - name: "Linux: Setup Dependencies"
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: DEBIAN_FRONTEND=noninteractive sudo apt-get -y --no-install-recommends install libgl-dev libasound2-dev libpulse-dev

      - name: Build zlib
        run: |
          scripts/build.sh zlib

      - name: Build non-Windows
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          scripts/build.sh libpng
          scripts/build.sh libjpeg-turbo
          scripts/build.sh openssl

      - name: Build
        run: |
          scripts/build.sh glew
          scripts/build.sh SDL2
          scripts/build.sh libogg
          scripts/build.sh libvorbis
          scripts/build.sh libmodplug
          scripts/build.sh SDL2_mixer
          scripts/build.sh freetype -DCMAKE_DISABLE_FIND_PACKAGE_HarfBuzz=TRUE
          scripts/build.sh harfbuzz
          scripts/build.sh freetype

      - name: Remove bin
        run: rm -r output/bin

      - name: Result
        run: ls -R output

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.env }}-${{ matrix.arch }}
          path: |
            output/*

      - name: Pack
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          cd output
          tar czf lc_deps-${{ matrix.env }}-${{ matrix.arch }}.tar.gz *

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: output/lc_deps-${{ matrix.env }}-${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
